[package]
name = "ferris_watch"
version = "0.1.0"
authors = ["otofu-square <otofu.square@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.6"
env_logger = "0.6.0"
failure = "0.1.3"
signal-hook = "0.1.6"
clap = "2.32.0"
pancurses = "0.16.0"
